/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.JTextField;
import models.AdminDirectory;
import models.Admins;
import models.CityDirectory;
import models.CommunityDirectory;
import models.Doctor;
import models.DoctorDirectory;
import models.EncounterDirectory;
import models.HospitalDirectory;
import models.Patient;
import models.PatientDirectory;
import models.PersonDirectory;
import view.Admin.AdminJFrame;
import resources.CreateDefaultData;
import view.Doctor.DoctorAdminJFrame;



public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    // initialize objects
    public static CommunityDirectory communityDirectory = new CommunityDirectory();
    public static CityDirectory cityDirectory = new CityDirectory();
    public static HospitalDirectory hospitalDirectory = new HospitalDirectory();
    public static DoctorDirectory doctorDirectory  = new DoctorDirectory();
    public static PersonDirectory personDirectory = new PersonDirectory();
    public static PatientDirectory patientDirectory = new PatientDirectory();
    public static EncounterDirectory encounterDirectory = new EncounterDirectory();
    public static AdminDirectory adminDirectory = new AdminDirectory();
    //public static Doctor doctorMain = new Doctor();
    
    public MainJFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(102, 102, 102));
        CreateDefaultData.createData();
        setLocationRelativeTo(null);
        //lblComment.setText("Enter Admin Credentials");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbChoice = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        lbl_title.setBackground(new java.awt.Color(153, 153, 153));
        lbl_title.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(204, 153, 0));
        lbl_title.setText("     HHS.gov");

        jLabel1.setText("Please select the login type");

        cbChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Doctor", "Patient" }));
        cbChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChoiceActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("U.S. Department of Health & Human Services");

        jLabel3.setText("Username :");

        jLabel4.setText("Password :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(txtPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(lblError))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed
/*if (cbChoice.getSelectedItem().toString().equals("Admin")){
            lblComment.setText("Enter Admin Credentials");}
        if (cbChoice.getSelectedItem().toString().equals("Doctor")){
            lblComment.setText("Enter Doctor Credentials");}
        if (cbChoice.getSelectedItem().toString().equals("Patient")){
            lblComment.setText("Enter Patient Credentials");}*/
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (cbChoice.getSelectedItem().toString().equals("Admin")){
            ArrayList<Admins> adminList = new ArrayList<>();
            adminList =adminDirectory.getAdminsList();
            for(Admins a : adminList){
                if (txtUsername.getText().equals(a.getUsername()) && txtPassword.getText().equals(a.getPassword())){
                    this.dispose();
                    new AdminJFrame().setVisible(true);
                }
                else{
                    lblError.setText("Invalid Credentials");
                    lblError.setForeground(new java.awt.Color(255, 0, 0));
                }
            }
            
        }
        
        if (cbChoice.getSelectedItem().toString().equals("Doctor")){
            ArrayList<Doctor> doctorList= new ArrayList<>();
            doctorList = doctorDirectory.getDoctorList();
            
            for(Doctor d : doctorList){
                if (txtUsername.getText().equals(d.getPerson().getUsername()) && txtPassword.getText().equals(d.getPerson().getPassword())){
                    this.setVisible(false);
                    this.dispose();
                    new DoctorAdminJFrame("doc",d.getPerson().getUsername()).setVisible(true);
                }
                else{
                    lblError.setText("Invalid Credentials");
                    lblError.setForeground(new java.awt.Color(255, 0, 0));
                }
            }
        }
        
        if (cbChoice.getSelectedItem().toString().equals("Patient")){
            
            ArrayList<Patient> patientList = new ArrayList<>();
            patientList = patientDirectory.getPatientList();
            for(Patient p : patientList){
                if (txtUsername.getText().equals(p.getPerson().getUsername()) && txtPassword.getText().equals(p.getPerson().getPassword())){
                    this.dispose();
                    new AdminJFrame().setVisible(true);
                }
                else{
                    lblError.setText("Invalid Credentials");
                    lblError.setForeground(new java.awt.Color(255, 0, 0));
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    // public functions
    public static void defaultSearchText(JTextField txtSearch, String content) {
        String defaultValue = content;
        txtSearch.setText(defaultValue);
	txtSearch.setForeground(Color.gray);

	// Add listener
	txtSearch.addFocusListener(new FocusAdapter() {
		@Override
		public void focusGained(FocusEvent e) {
			if (txtSearch.getText().equals(defaultValue)) {
				txtSearch.setForeground(Color.black);
				txtSearch.setText("");
			}
			super.focusGained(e);
		}

		@Override
		public void focusLost(FocusEvent e) {
			if (txtSearch.getText().equals("")) {
				txtSearch.setForeground(Color.gray);
				txtSearch.setText(defaultValue);
			}
			super.focusLost(e);
		}
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables



}