/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.employee.application.ui;

import com.employee.application.EmployeeHistory;
import com.employee.application.EmployeeInfo;
import java.util.Date;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author madan
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    String selectedImagePath;
    EmployeeHistory employeeHistory;
    ButtonGroup group = new ButtonGroup();
    Date startDate;
    SimpleDateFormat formatter;
    public CreateJPanel(EmployeeHistory employeeHistory) {
        
        initComponents();
        this.employeeHistory = employeeHistory;
        lblImageIcon.setText("");
        lblImageIcon.setVisible(false);    
        group.add(rbtnMale);
        group.add(rbtnFemale);
        formatter = new SimpleDateFormat("MM/dd/yyyy");
        formatter.setLenient(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblGender = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblPosition = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        lblContactNum = new javax.swing.JLabel();
        txtContactNum = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        lblMailId = new javax.swing.JLabel();
        txtMailId = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblImageIcon = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        lblError = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGender.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblGender.setText("*Gender:");
        jPanel4.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 208, 100, 22));

        lblTeamInfo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblTeamInfo.setText(" Team Information:");
        jPanel4.add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 237, -1, 22));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 492, -1, -1));

        lblPosition.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblPosition.setText(" Position:");
        jPanel4.add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 265, 100, 22));

        lblLevel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblLevel.setText(" Level:");
        jPanel4.add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 299, 100, 22));

        txtTeamInfo.setText("Enter Team Information");
        txtTeamInfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTeamInfoFocusGained(evt);
            }
        });
        txtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamInfoActionPerformed(evt);
            }
        });
        jPanel4.add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 237, 190, -1));

        txtEmpId.setText("Enter Employee ID");
        txtEmpId.setName(""); // NOI18N
        txtEmpId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmpIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmpIdFocusLost(evt);
            }
        });
        jPanel4.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 102, 190, -1));

        txtName.setText("Enter Name");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 136, 190, -1));

        txtAge.setText("Enter Age");
        txtAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAgeFocusLost(evt);
            }
        });
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel4.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 170, 190, -1));

        txtLevel.setText("Enter Level");
        txtLevel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLevelFocusGained(evt);
            }
        });
        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });
        jPanel4.add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 299, 190, -1));

        txtPosition.setText("Enter Position");
        txtPosition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPositionFocusGained(evt);
            }
        });
        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });
        jPanel4.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 265, 190, -1));

        txtStartDate.setText("Enter Date in MM/DD/YYYY");
        txtStartDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStartDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStartDateFocusLost(evt);
            }
        });
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });
        jPanel4.add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 327, 190, -1));

        lblContactNum.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblContactNum.setText("*Contact Number:");
        jPanel4.add(lblContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 361, 100, 22));

        txtContactNum.setText("Enter Contact Number");
        txtContactNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContactNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactNumFocusLost(evt);
            }
        });
        txtContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumActionPerformed(evt);
            }
        });
        jPanel4.add(txtContactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 361, 190, -1));

        lblStartDate.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblStartDate.setText("*Start Date:");
        jPanel4.add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 327, 100, 22));

        lblMailId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblMailId.setText("*Mail ID:");
        jPanel4.add(lblMailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 395, 100, 22));

        txtMailId.setText("Enter Email");
        txtMailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMailIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailIdFocusLost(evt);
            }
        });
        txtMailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtMailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 395, 190, -1));

        lblPhoto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblPhoto.setText(" Photo:");
        jPanel4.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 438, -1, -1));

        btnUpload.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpload.setText("UPLOAD");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 435, 130, -1));

        lblTitle.setBackground(new java.awt.Color(204, 204, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE NEW EMPLOYEE ");
        lblTitle.setToolTipText("");
        jPanel4.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 34));

        lblEmpId.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblEmpId.setText("*Employee ID:");
        jPanel4.add(lblEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 102, 100, 22));

        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblName.setText("*Name:");
        jPanel4.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 136, 100, 22));

        lblAge.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblAge.setText("*Age: ");
        jPanel4.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 170, 100, 22));

        lblImageIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(lblImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 102, 100, 100));

        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        jPanel4.add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 208, -1, -1));

        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        jPanel4.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 208, -1, -1));
        jPanel4.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 469, 252, 17));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Boolean validationFailed(){
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        if ("Employee ID should be integer".equals(txtEmpId.getText()) || "Enter Employee ID".equals(txtEmpId.getText()) ){
            txtEmpId.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, Check red fields");
            return true;
        }
        if ("Name Pattern is incorrect".equals(txtName.getText()) || "Enter Name".equals(txtName.getText()) ){
            txtName.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, Check red fields");
            return true;
        }
        if ("Age should be integer".equals(txtAge.getText()) || "Enter Age".equals(txtAge.getText()) ){
            txtAge.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, Check red fields");
            return true;
        }
        if ("Enter Team Information".equals(txtTeamInfo.getText())){
            txtTeamInfo.setText(""); 
        }
        if ("Enter Contact Number".equals(txtContactNum.getText()) || "Enter 10 digit Number".equals(txtContactNum.getText()) ){
            txtContactNum.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, check red fields");
            return true;
        }
        if ("Email is incorrect".equals(txtMailId.getText()) || "Enter Email".equals(txtMailId.getText()) ){
            txtMailId.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, check red fields");
            return true;
         }
         
        if ("Date should be in MM/DD/YYYY".equals(txtStartDate.getText()) || "Enter Date in MM/DD/YYYY".equals(txtStartDate.getText()) ){
            txtStartDate.setForeground(new java.awt.Color(255, 0, 0));
            lblError.setText("There is some error saving, Check red fields");
            return true;
        }
        
        if ("Enter Position".equals(txtPosition.getText())){
            txtPosition.setText(""); 
        }
        
        if ("Enter Level".equals(txtLevel.getText())){
            txtLevel.setText(""); 
        }
 
        
        
        return false;
    }
    public boolean checkEmployeeUnique(){
        ArrayList<EmployeeInfo> listEmployee = employeeHistory.getHistory();
        Boolean found = false;
        for (EmployeeInfo individualEmployee : listEmployee) {
            if(Integer.parseInt(txtEmpId.getText()) == individualEmployee.getEmpId()){
               lblError.setText("Employee ID already exists, Enter Unique ID");
               lblError.setForeground(new java.awt.Color(255, 0, 0));
               found = true;
            }
        }
        if (found) {
            return found;
        }
        else{
        return false;
        }
    }

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if (checkEmployeeUnique()){
            return;
        }
        if (validationFailed()){
            return;
        }
        
        String name = txtName.getText();
        int empId = Integer.parseInt(txtEmpId.getText());
        int age = Integer.parseInt(txtAge.getText());
        String gender = getSelectedOption();
        String level = txtLevel.getText();
        String teamInfo = txtTeamInfo.getText();
        String position = txtPosition.getText();
        Long contact = Long.parseLong(txtContactNum.getText());
        String mailId= txtMailId.getText(); 
        try 
        { 
            startDate = formatter.parse(txtStartDate.getText()); 
            System.out.print(startDate);
        }  
        catch (ParseException e)  
        { 
            txtStartDate.setText("Date should be in DD/MM/YYYY");
            txtStartDate.setForeground(new java.awt.Color(255, 0, 0));
            return;
        }
         
        
        
        EmployeeInfo employeeInfo= employeeHistory.addNewEmployee();
        employeeInfo.setName(name);
        employeeInfo.setEmpId(empId);
        employeeInfo.setAge(age);
        employeeInfo.setGender(gender);
        employeeInfo.setStartDate(startDate);
        employeeInfo.setLevel(level);
        employeeInfo.setTeamInfo(teamInfo);
        employeeInfo.setPosTitle(position);
        employeeInfo.setMailId(mailId);
        employeeInfo.setContact(contact);
        //Set the image to employeeinfo function
        employeeInfo.setProfilePicture(selectedImagePath);

        JOptionPane.showMessageDialog(this,"New Employee record saved");
       
        viewRefresh();

    }//GEN-LAST:event_btnSaveActionPerformed
    public String getSelectedOption() {
        Enumeration<AbstractButton> radioButtons = group.getElements();
        while (radioButtons.hasMoreElements()) {
            AbstractButton currentRadioButton = radioButtons.nextElement();
            if (currentRadioButton.isSelected()) {
                return currentRadioButton.getText();
            }
        }
        return null;
    }
    public void viewRefresh(){
        txtName.setText("");
        txtEmpId.setText("");
        txtAge.setText("");
        txtStartDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtPosition.setText("");
        txtContactNum.setText("");
        txtMailId.setText("");
        lblImageIcon.setVisible(false);
        lblImageIcon.setIcon(null);
        btnUpload.setText("Upload");
        rbtnFemale.setSelected(false);
        rbtnMale.setSelected(false);
        lblError.setText("");
    }
    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void txtContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumActionPerformed

    private void txtMailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailIdActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int ShowOpenDialogue = browseImageFile.showOpenDialog(null);
        File selectedImageFile = browseImageFile.getSelectedFile();
        selectedImagePath = selectedImageFile.getAbsolutePath();
        //lblImageIcon.setVisible(true);
        //Display image on jLablel1
        ImageIcon ii = new ImageIcon(selectedImagePath);
        //Resize image
        Image image = ii.getImage().getScaledInstance(100,100, Image.SCALE_SMOOTH);
        lblImageIcon.setIcon(new ImageIcon(image));
        lblImageIcon.setVisible(true);
        btnUpload.setText("Change Image");

        
        
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z- ]{1,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtName.getText());
        if(!match.matches()){
            txtName.setText("Name Pattern is incorrect");
            txtName.setForeground(new java.awt.Color(255, 0, 0));
        }
    }//GEN-LAST:event_txtNameFocusLost
    
    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        txtName.setText(null);
        txtName.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtNameFocusGained

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
        rbtnFemale.setSelected(false);
        rbtnMale.setSelected(true);
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
        rbtnFemale.setSelected(true);
        rbtnMale.setSelected(false);
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void txtEmpIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpIdFocusGained
        // TODO add your handling code here:
        txtEmpId.setText(null);
        txtEmpId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtEmpIdFocusGained

    private void txtEmpIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpIdFocusLost
        // TODO add your handling code here:
                try 
		{ 
                    Integer.parseInt(txtEmpId.getText());  
		}  
		catch (NumberFormatException e)  
		{ 
                    txtEmpId.setText("Employee ID should be integer");
                    txtEmpId.setForeground(new java.awt.Color(255, 0, 0)); 
		}  
    }//GEN-LAST:event_txtEmpIdFocusLost

    private void txtAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusGained
        // TODO add your handling code here:
        txtAge.setText(null);
        txtAge.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtAgeFocusGained

    private void txtAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAgeFocusLost
        // TODO add your handling code here:
                try 
		{ 
                    Integer.parseInt(txtAge.getText());  
		}  
		catch (NumberFormatException e)  
		{ 
                    txtAge.setText("Age should be integer");
                    txtAge.setForeground(new java.awt.Color(255, 0, 0)); 
		} 
    }//GEN-LAST:event_txtAgeFocusLost

    private void txtTeamInfoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTeamInfoFocusGained
        // TODO add your handling code here:
        txtTeamInfo.setText(null);
    }//GEN-LAST:event_txtTeamInfoFocusGained

    private void txtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamInfoActionPerformed

    private void txtContactNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactNumFocusGained
        // TODO add your handling code here:
         txtContactNum.setText(null);
        txtContactNum.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtContactNumFocusGained

    private void txtContactNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactNumFocusLost
        // TODO add your handling code here:
       String PATTERN1="^[0-9]{9,10}$";
       Pattern patt=Pattern.compile(PATTERN1);
       Matcher match=patt.matcher(txtContactNum.getText().toString());
       if(!match.matches())
       {
           txtContactNum.setText("Enter 10 digit Number");
           txtContactNum.setForeground(new java.awt.Color(255, 0, 0));
       }
    }//GEN-LAST:event_txtContactNumFocusLost

    private void txtMailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailIdFocusGained
        // TODO add your handling code here:
        txtMailId.setText(null);
        txtMailId.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_txtMailIdFocusGained

    private void txtMailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailIdFocusLost
        // TODO add your handling code here:
        String PATTERN1="^(.+)@(.+)$";
        Pattern patt=Pattern.compile(PATTERN1);
        Matcher match=patt.matcher(txtMailId.getText());
        if(!match.matches())
        {
            txtMailId.setText("Email is incorrect");
            txtMailId.setForeground(new java.awt.Color(255, 0, 0));
        }
    }//GEN-LAST:event_txtMailIdFocusLost

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtStartDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartDateFocusGained
        // TODO add your handling code here:
        txtStartDate.setText(null);
        txtStartDate.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtStartDateFocusGained

    private void txtStartDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartDateFocusLost
        // TODO add your handling code here:
                try 
		{ 
                    formatter.parse(txtStartDate.getText());  
		}  
		catch (ParseException e)  
		{ 
                    txtStartDate.setText("Date should be in MM/DD/YYYY");
                    txtStartDate.setForeground(new java.awt.Color(255, 0, 0)); 
		} 
    }//GEN-LAST:event_txtStartDateFocusLost

    private void txtPositionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPositionFocusGained
        // TODO add your handling code here:
        txtPosition.setText(null);
    }//GEN-LAST:event_txtPositionFocusGained

    private void txtLevelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLevelFocusGained
        // TODO add your handling code here:
        txtLevel.setText(null);
    }//GEN-LAST:event_txtLevelFocusGained

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
    /**/

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContactNum;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImageIcon;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMailId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMailId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
