/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Doctor;

import models.CityDirectory;
import models.CommunityDirectory;
import models.DoctorDirectory;
import models.EncounterDirectory;
import models.HospitalDirectory;
import models.PatientDirectory;
import models.PersonDirectory;
import view.Admin.HospitalAdmin.*;
import view.Admin.AdminJFrame;
import view.MainJFrame;


public class DoctorMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdminJFrame
     */
 

    
    public DoctorMainJFrame() {
        initComponents();
        workArea.setSize(900, 900);
        setLocationRelativeTo(null);
        DoctorEncounterViewUpdate encView = new DoctorEncounterViewUpdate();
        splitPane.setRightComponent(encView);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnVitalSign = new javax.swing.JButton();
        btn_encounters = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        controlPanel.setBackground(new java.awt.Color(153, 255, 204));

        btnVitalSign.setBackground(new java.awt.Color(255, 255, 255));
        btnVitalSign.setForeground(new java.awt.Color(51, 51, 255));
        btnVitalSign.setText("Vital Signs");
        btnVitalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalSignActionPerformed(evt);
            }
        });

        btn_encounters.setBackground(new java.awt.Color(255, 255, 255));
        btn_encounters.setForeground(new java.awt.Color(51, 51, 255));
        btn_encounters.setText("Encounters");
        btn_encounters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encountersActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setForeground(new java.awt.Color(51, 51, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout)
                    .addComponent(btn_encounters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVitalSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnLogout)
                .addGap(112, 112, 112)
                .addComponent(btn_encounters)
                .addGap(18, 18, 18)
                .addComponent(btnVitalSign)
                .addContainerGap(776, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalSignActionPerformed
        //PatientViewUpdate d = new PatientViewUpdate();
        //splitPane.setRightComponent(d);
    }//GEN-LAST:event_btnVitalSignActionPerformed

    private void btn_encountersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encountersActionPerformed
        EncounterViewUpdate d = new EncounterViewUpdate();
        splitPane.setRightComponent(d);
    }//GEN-LAST:event_btn_encountersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMainJFrame().setVisible(true);
            }
        });
    }
    
    
    public void setHospitalCreateView() {                                               
        // TODO add your handling code here:
        HospitalCreate createPanel = new HospitalCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setDoctorCreateView() {                                               
        // TODO add your handling code here:
        DoctorCreate createPanel = new DoctorCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setEncounterCreateView() {                                               
        // TODO add your handling code here:
        EncounterCreate createPanel = new EncounterCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setPatientCreateView() {                                               
        // TODO add your handling code here:
        PatientCreate createPanel = new PatientCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setEncounterUpdateView() {                                               
        // TODO add your handling code here:
        EncounterViewUpdate createPanel = new EncounterViewUpdate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setDoctorUpdateView() {                                               
        
        DoctorViewUpdate createPanel = new DoctorViewUpdate();
        splitPane.setRightComponent(createPanel);
    }
    public void setPatientUpdateView() {                                               
        
        PatientViewUpdate createPanel = new PatientViewUpdate();
        splitPane.setRightComponent(createPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVitalSign;
    private javax.swing.JButton btn_encounters;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}

